# Quit Lit or What the Hell Happened? 

Quit lit is rarely defined but most academics have seen or heard of its prominence in recent years. These documents are a particular type of discussion of the challenges in higher education. They often take a first person perspective and reflect both on the individual’s story and how this connects to the larger questions within the academy and higher education. By starting with an incomplete typology of perspectives on why people leave the academy, we get a sense of the variety of stories that are told and can reflect on how these themes may emerge in our own stories. 
The point is to begin to own one’s story and to take seriously how our own individual positions and experiences are connected to the larger world. Being willing to examine our own story in light of the larger structure, industry and mechanisms that we have been a part of can ease the individual burden and begin the healing process.  

## Readings: 
- [Garber, Megan. “The Rise of Quit Lit” - Atlantic](https://www.theatlantic.com/entertainment/archive/2015/09/dont-quit-your-day-job/404671/) 
- [Schuman, Rebecca “Thesis Hatement” - Slate](http://www.slate.com/articles/life/culturebox/2013/04/there_are_no_academic_jobs_and_getting_a_ph_d_will_make_you_into_a_horrible.html)
- [Bartram, Erin - “The Sublimated Grief of the Left Behind”](http://erinbartram.com/uncategorized/the-sublimated-grief-of-the-left-behind/)
- [Neff, Ali Colleen - “On Academic Precarity”](http://www.alicolleenneff.com/blog/2017/11/8/on-academic-precarity)
- [Lee, Oliver - “I have one of the best jobs in Academia. Here’s why I’m walking away” - Vox](%20https://www.vox.com/2015/9/8/9261531/professor-quitting-job) 
- [Conditionally Accepted, “Dear Department, I Quit.”](%20https://conditionallyaccepted.com/2015/06/16/quit/)
- [Harbin, Alison - “Why I Left Academia Part I & II”](%20https://www.allisonharbin.com/post-phd/why-i-left-academia-part-1)
- [Dunn, Sydni - “Why So Many Academics Quit and Tell”](https://chroniclevitae.com/news/216-why-so-many-academics-quit-and-tell) 
- For more, see the list of pieces in a Google Doc:[”Quit Lit: The Vitae List”](%20https://docs.google.com/spreadsheets/d/1OODoiZKeAtiGiI3IAONCspryCHWo5Yw9xkQzkRntuMU/edit#gid=0) 

## Homework: 
1) After reading the above quit lit, find more that fits with your experiences. Consider the themes and note which ones fit best with your story. 
Chose among any combination of the following topics/themes: academic precarity and economic instability, the contingent labor market and low-paid adjunct positions, not enough tenure track jobs and the competition for tenure track positions, academia is not for me, academia is for me but I didn’t get a job, academia is for me but I hate teaching, unfair teaching burdens, student apathy, student entitlement, unprepared students, student as customer, the rise of online education, increased student tuition, student loan bloat, the broken hiring process, the broken tenure process, the broken academic publishing process, decreased university funding, increased higher education administration, low faculty salaries, declining funding for research, the declining liberal arts, anti-intellectualism, classism, geographic isolation, loneliness, grief, the “two body” problem, having a child, having a child with special needs, having small children, incompatible careers, family illness, divorce, everyday institutional racism and microaggressions, mental illness, workaholism, everyday sexism, sexual harrassment, sexual assault, assault, verbal abuse, gaslighting, unequal emotional labor workload, illegal behavior, institutional politics and infighting, sabotage, the trap of post doctoral positions, the trap of visiting assistant positions, the trap of adjuncting, dropping out of a Ph.D program, the desire to do work that matters, the desire to do manual work or the desire to have a life. 
2) Write your own quit lit piece. If you have not already left, imagine you have or will soon leave. If you have left, make your writing cathartic.   
Optional Extra credit: Let someone (or a lot of someones) read your quit lit piece. 