#You Are Not Alone

This unit reminds you that regardless of your experience, there are others who have had similar experiences and who have left the academy. There is even some evidence that you will (gasp) be happier if you leave. 

There are a myriad of people out there who are doing work that will help you even if you have no money, there are books you can check out from the library, concrete steps you can take and people who will talk to you. 

We will start with general resources and then follow up with specific resources for certain groups. 

## Readings

- What I wish I had Known - Beth M. Duckles 
- [The Professor is In](http://theprofessorisin.com/)
- [Imagine Ph.D.](https://www.imaginephd.com/)
- [Beyond the Professoriate](https://community.beyondprof.com/) 
- [Perel, Greta - “What Happens When Academics Quit? Good Things it Turns Out.”](https://www.timeshighereducation.com/blog/what-happens-when-academics-quit-good-things-it-turns-out)

## Resources for Women 
Women often face very specific challenges with leaving the academy. There are a number of resources that may help you work with and heal from these challenges as well as assisting you in getting your story back into your own hands.  

-  [Tara Mohr, Playing Big](https://www.taramohr.com/book/) 
> “Gave me lots of solid information about women and ambition, and eventually connected me to smart women also trying to figure shit out.


## Resources for People of Color 


## Doing your Human Homework
Leaving the academy is a huge life shift and as the child of two psychologists, I'm keen to encourage people to work through the things that have brought them emotional pain. Basically, I want you to do your human homework. 

Human Homework is the act of facing and working with your fear, shame and emotions so that you can heal. It's not something you ever finish doing but it is something that you need when you're going through difficult times. 

Doing your human homework regardless of who you are will make you a more effective and whole human being. I strongly believe that you are not broken and the world has need of your intelligence and skills. 

I do not have opinions about what specific method would work best for you to do this work. I just encourage you to do it. 

Below is a list of resources that might help. Some might intrigue you, while others may turn you off. Just find the resources or method that do speak to you and work with those.  

- Transitions Book - William Bridges 
- Nonviolent Communication 
- Sedona Method 
- [Parker Palmer and the Center for Courage and Renewal](http://www.couragerenewal.org/) A former academic and writer, Parker writes about his experiences and share insights from the Quaker tradition and his time with the retreat center Pendle Hill. His books reflect on how to "let your life speak" and to look for wholeness in your life. He works with the Center for Courage and Renewal to create retreats and other seminars.  
- [Brene Brown] Brene Brown is a professor of social work at UT Austin who did a TEDx talk that went viral about vulnerability. She has written several books based on her research. Among them are Rising Strong
- Pema Chodron 
- Landmark Forum
- Last Mask Shamanic Center 
- More to Life
- The Road Less Traveled - Peck 
- [Leadership Embodiment - Wendy Palmer](http://www.leadershipembodiment.com/) 
- The Big Leap (???)
- [Martha Beck](https://marthabeck.com/) Martha is a former academic who has written memoirs, self help books and has created a tribe of people who are focused on finding direction. Among her books: Steering By Starlight, Finding Your Way in a Wild New World. 
- [Man's Search for Meaning - Viktor Frankl](https://en.wikipedia.org/wiki/Man%27s_Search_for_Meaning) A book written by a psychologist, chronicling his experiences in Auchwitz and finding meaning in life. 
- ["Uncertainty: Turning Fear and Doubt into Fuel For Brilliance - Jonathan Fields](http://www.jonathanfields.com/)
- ["The Power of Meditation: A 28 Day Program - Sharon Saltzberg](https://www.sharonsalzberg.com/)
- [The Dance of Anger - Harriet Lenrner](https://www.harrietlerner.com/)

