# Networking 

This class will demystify and simplify the task of networking by encouraging you to note your strengths (yes introverts have networking strengths) and to give you a chance to play around with and consider how best to network into new ideas. 

The truth is, that getting a new job, starting a new career, or even being a public academic requires networking. I am not suggesting that you change who you are, or do anything that turns you into a smarmy salesperson. You gotta be you.  

## Resources 
- [“Bajuniemi, Abby - “Networking Strategies for Beginners”](https://code.likeagirl.io/networking-strategies-for-beginners-986fe0b3efdf) 
- Linkedin 
- Meetup.com 
- Twitter
- Facebook Groups 

## Homework 

 1) Create social media profiles for Linked In, Twitter and Meetup. If you dislike or are nervous about being on one or more of these platforms consider creating very specific boundaries around how you choose to use them.  For instance, you might decide that you will not friend people on Linked in that were in your classes. Or you might only tweet things that you think people who are in your field would be interested in. Or you might decide 
 
2a) Connect with five new people on LinkedIn that you already know. Write them a short personal note saying something along the lines of: “It’s great to see you on here, hope you are doing well. - YourName” or “I was thinking about you the other day and it’s good to look you up on here and see you’re doing well.” - YourName or “I saw this article/anecdote/event/meme and thought of you. Hope you’re doing well.” - YourName 

2b) Follow someone you think is interesting on Twitter. Read their tweets. 

2c) Look for some Meetups you might consider going to. Put one on the calendar. 

2d) Join a new Facebook Group and respond to or “like” someone’s post. 


