# A Job 
There are a thousand and one books out there on how to find a job and a ton of people who can help. That said, it can be somewhat overwhelming to approach those when you’re an academic. We face very specific challenges like - how do I turn my CV into a resume? or how do I talk to people about my research without boring them to tears? or what on earth do I have to share that’s marketable? I have a few brief thoughts about the act of trying to find a job after being an academic, but there are resources.  
First, recognize that you have skills. Even if you have the most esoteric dissertation in the world, you have skills and often can teach them or use them in service to all kinds of projects. Consider what you did love about academia. Was it reading? Writing? Teaching? Was it the content you were working on? Was it the methods you were using? Did you like the meetings or prefer to hide out in the lab/library/archives? Consider your answers to these questions as you look for your job and try to find places where those skills are valued.  
Second, the path of finding your post ac job can be trial and error. It often does not follow a clear path and there isn’t anyone else who can know what the next step is for you to take. It can be bewildering, frustrating and incredibly scary for academics who have had the path laid out for them (take these classes, then do these exams, then write this paper etc). This kind of figure-it-out-as-you-go mentality is actually normal for non academics. If you need to be reminded of this, go talk to a friend who never went to grad school and ask them how they got their current job. You might be surprised. 
Third, you gotta pay your bills. Don’t discard jobs that are completely different than your academic work, if they fit for you and make you happy. There is no shame in doing work that is non academic to make ends meet. Do side gigs if you need to, start up an etsy shop, work with high school kids on their SAT prep, teach art classes, do freelance writing or editing. Consider arranging flowers, being a cheesemonger, becoming a sommelier, a bike mechanic, doing community organizing, running online seminars, Let me reiterate, there is no shame in any of these jobs. Or rather, you can feel ashamed if you really want to but you might consider that most people are not judging you. 
- [Jobs on Toast](http://jobsontoast.com/)
- [Versatile Ph.D.](https://versatilephd.com/)
- [https://medium.com/design-leadership/benefits-of-a-non-linear-design-career-path-d0add49a90c8](https://medium.com/design-leadership/benefits-of-a-non-linear-design-career-path-d0add49a90c8)
- Side gig book - Chris Guillibeau 
- [https://www.insidehighered.com/news/2017/12/18/study-humanities-and-social-science-phds-working-outside-academe-are-happier-their?utm\_source=Inside+Higher+Ed](https://www.insidehighered.com/news/2017/12/18/study-humanities-and-social-science-phds-working-outside-academe-are-happier-their?utm_source=Inside+Higher+Ed)

## Homework 
- Write down ten jobs you would like to do. Don’t think about it, just write them down. Doesn’t matter if they’re silly or strange. Feel free to put circus performer, professional basketweaver or person who does nature walks for a living. Do this every day for a week. 
- Ask someone you trust to tell you what they think you’re good at. Listen without interrupting. Write down what they say. 
