# Creativity 
It may seem strange for me to have a week on creativity but in my own recovery from academia I’ve found it to be an incredibly potent tool for dealing with what I feel and think as well as a way to feel more content and happy in life. 

I believe we are all creative. I don’t think there are any among us who are not creative. For many academics, the creative urges have been quashed by the desire to please those who we have looked up to in our school years. We may also believe ourselves not to be creative, or to have taken to hear the kind of language that tells us that a “true” scientist/historian/professor isn’t a creative person. 

My number one recommendation is Julia Cameron’s “The Artist’s Way”. In that book she describes much of what has caused many of us academics a lot of pain. She does so with compassion and grace and she slowly, steadily and lovingly encourages the nascent artists inside of us out of their shell. 

- Julia Cameron “The Artist’s Way” 
- SARK’s book
- Ignore Everybody - MacLeod
- Art and Fear 

## Homework
- Do one thing that seems fun and creative. A few ideas: Play with legos, cook a meal, doodle on a piece of scrap paper until the page is filled up, write bad poetry about something you can see in the room you’re in now, take a train, take a pottery class, bus or car trip and spend the entire trip looking out of the window, hum a song, play an instrument, drum on the tabletop, paint, garden, sew, knit, crochet, find a youtube video that teaches you a dance step, make snow/sand angels, make splashes in the water and watch the shape they make, eat your favorite childhood snack, walk somewhere interesting, skip stones, build a little teepee out of sticks in the woods, make a fire, do karaoke, read a poem or a speech out loud, watch a movie, make paper airplanes, play with arduino, go see a play, do a zumba class, learn a few words in another language, watch a dance performance and anything else your heart desires. 