---
title: "Academic Recovery"
---
# Academic Recovery 

In the first year after leaving my tenure track job, when people asked what my work was, I joked that I was a recovering academic. In reality I was bumbling around trying to figure out how to sell my skills as a freelance researcher and I didn't know what it meant to not be a professor. Despite the fact that I had been flirting with leaving the academy for a while, it was an odd thing not to fall back on being a professor when people asked. I had either wanted to be a professor or been a professor for over a decade. 

It's worth exploring the idea of recovering from academia. I realize that it's a made up term, but it strikes me that many of us have things we're not happy about that indicate why we've left. What is it exactly that we're recovering FROM? After spending quite a bit of time listening to a lot of people who have left or are considering leaving the academy, there are different answers to that question. 

Many who leave academia describe the "cult-like" behaviors they saw and some may struggle with feeling a longing for jobs that are connected to the academic mission, no matter how precarious, badly paying or marginal. Some postacs mention feeling an almost addiction to teaching, or research, or being at a university. Some of us liked the work, or loved getting to read so much. Some of us felt happy to be surrounded by books, or loved the intellectual stimulation and people who understood when we geeked out. Some of us got excited by the teaching, the rythms of a classroom, the way we could see minds grow.

The metaphor addiction metaphor is not perfect here, since what we are talking about has to do not with a substance but rather a set of institutions, but it is worth asking, what is it about academia that hooked you? What did you love? What were your hopes? 

Many of us too have felt that there were things that happened which were painful and difficult. Here we might use another metaphor - that of a broken or a badly ended relationship (you can choose the metaphor that best fits for you) This too is imperfect as we are again talking about an institution and not an individual person. Yet I think the metaphor is a useful one and may illuminate the differing types of things a recovering academic might be recovering from. 

Consider walking through the different types of reasons for breaking up with the academy we might see: 

### Academia broke up with me
* I’m a graduate student and I didn’t pass my exams/my dissertation. 
* I’m a graduate student and I didn’t get an academic job but I’m graduating anyway. 
* I’m visiting/adjunct professor and this job is ending. 
* I was denied tenure. 

## I broke up with Academia  
* I am too physically/mentally/emotionally ill to keep doing this.
* I was abused (emotionally/verbally/sexually). 
* I can’t make enough money/pay back my loans with this job. 
* I don’t want tenure here. 
* I don’t believe in what I’m doing anymore. 
* My family/children are in need and I have to be with them. 
* My partner got a job somewhere else and it was too good to turn it down. 
* I got a job offer and there were too many good reasons to take it.


## It’s complicated 
* I’m a visiting/adjunct and I am not making ends meet. 
* I’m not a cis, hetero white man so I experience microaggressions daily. It is not sustainable.  
* I don't want to live in this geographic location.  
* My department is toxic. I can’t do this for much longer. 
* I’m a graduate student but the constant criticism/abuse is not good for me. I’m not sure about academia as a career. 
* I have an academic job, but there is an end date. What do I do if this academic thing doesn’t work? 
* I’m on the never-ending postdoc track and I just can’t do another one.
* I don’t know who I’d be if I’m not a teacher but everything else besides my students is awful. 
* I’m losing faith in what I’m doing. 


For all of these, there are particular things that hooked you into the academic lifestyle and probably different reasons why you might be feeling strong emotions. From 


If academia broke up with you, there is likely a disconnect between what you wanted to have happen and what happened and this manifests usually as strong emotions like grief and a sense of loss, anger and sadness. This is a set of emotions that you need to go through. There’s also probably a sense that you’re not sure WTF to do next . 

While still difficult, if you had a choice and did the breaking up yourself, you probably have some sort of contingency plan even if it's a bit vague. Yet still, there's no shortage of anxiety fIf you’re the kind of person who second guesses themselves) some anxiety. You may not fully know if this was the absolute right choice, but it might have been the right choice for your family, partnership, health, long term financial future and your heart and soul. If that is true for you, please know that all of these are entirely valid reasons to leave a job. 

You will likely know all of this and still feel a sense of loss. The difference is that you will have had more time in your discernment process to understand that this loss has some upsides. That’s not to say that leaving academia was necessarily what you wanted, but you may have felt that you had a choice. 

You still likely have the WTF do I do question. And you’re figuring out what happens next for you. 


This is a challenging place to be because the situation you’re in right now probably feels pretty shitty and you’re not sure that you want to keep doing it. At the same time.  



## How much time does it take?

* restore my sense of self 
* work through someon else's critique 

* separating what's you and what's the institution. 
Where were you harmed? where did you harm yourself?
Where did the institution harm you? 

There are three things I will say throughout the entirety of this book and I will repeat them in as many ways as possible 1) You are not alone 2) You have skills and 3) It can get better. 

## You Are Not Alone

Regardless of your experience, there are others who have had similar experiences and who have left the academy. There is even some evidence that you will (gasp) be happier if you leave. 

There are a myriad of people out there who are doing work that will help you even if you have no money, there are books you can check out from the library, concrete steps you can take and people who will talk to you. 

We will start with general resources and then follow up with specific resources for certain groups. 

## Readings

- What I wish I had Known - Beth M. Duckles 
- [The Professor is In](http://theprofessorisin.com/)
- [Imagine Ph.D.](https://www.imaginephd.com/)
- [Beyond the Professoriate](https://community.beyondprof.com/) 
- [Perel, Greta - “What Happens When Academics Quit? Good Things it Turns Out.”](https://www.timeshighereducation.com/blog/what-happens-when-academics-quit-good-things-it-turns-out)


