In the first couple of years after leaving academia, when people asked what I did, I joked that I was a "recovering academic". It was my way of talking to people about the weirdness of leaving an academic position for freelance jobs and not exactly having a clear plan for how everything was going to go. I wanted to be where I was, and I was doing ok. I just couldn't shake the feeling that academia was this large thing looming behind me as I talked to people. 

I noticed that when I used the phrase "recovering academic" with people who had NOT spent significant time in an academically focused graduate program, it was a decent icebreaker that had some humor to it. They'd sort of chuckle and they'd ask me what projects I had these days and what I had done before. It all seemed pretty normal. It was as if I had decided to leave an industry or a profession that hadn't been quite right for me (which - I had!). Just like someone might leave the aerospace industry to learn more about the construction industry. Sort of benign and mildly interesting, but not at all unusual. 

There was a palpable difference when people who understood what it meant to leave an academic position responded to the phrase. They knew exactly what I meant when I said I was a recovering academic. They didn't laugh, but instead they were often sincere and some of them even checked in to make sure I was doing ok. Some would tell me a story of someone they knew who had left or about their choice not to finish a PhD or their friend who had done something similar. They seemed to understand I had really left something and was in fact recovering.

The more this happened, the more I started to wonder about this phrase that I was using so lightly. Why was it that some people seemed to see this change that I had made as simply a change in my employment while other people were seeing this as a really big life change. Certainly, it was a big transition, but why was I still feeling so tied to the academy when I no longer received a paycheck from a university? 

If I was a recovering academic, I began to get curious about what was I recovering FROM? 

This question is the starting place of the post ac syllabus. What are we recovering from? What is the hold that academia has over us? I suspect there are as many answers to this question as there are recovering academics, but I would like to just say that if you feel like there is an invisible string that keeps you attached to the academy, you aren't alone. What is it that keeps us attached? What do we need to get over? 

I'm going to suggest that if we are going to actually recover from academia, It's important to get a handle on our own story, to figure out what happened to us, or perhaps what is still happening to us. Recovering from academia means responding to whatever pains and challenges happened to us, acknowledging the loss and and choosing to take new steps forward. We need to be able to talk about our story and be the owner of it. 

## Do I Have to Leave?

By the way, when we say recovering from academia, it doesn't mean you have to leave. Maybe it does, but maybe it doesn't. Certainly there are quite a number of us who thought we were always going to be professors and have found ourselves doing work outside the academy that is fulfilling. For some of us, we intended to leave but have found ourselves right back in a job we love but was different than we had imagined. Some of us are doing the same academic work but are also doing side gigs. Still more of us have found fulfilling careers outside the academy or with one toe inside, maybe doing a class here or there. 

Recovery looks like whatever you need it to look like.  

## Three Things

There are three things I will say as many ways as possible and from as many voices as I can throughout this course. In my experience of talking with Post Acs, these are the things you need to hear.   
1. You are not alone. 
2. You have skills. 
3. It can get better. 

Regardless of what you've gone through, there are others who have had similar experiences. Maybe not exactly the same thing you've experienced but there are people who get it and who have moved through something similar. It may feel like no one else who has been where you are, but really truly - you're not alone. 

If you made it into a graduate program, you have skills. If you made it out of a graduate program, you also have skills. I know this can be hard to remember if you've spent a bunch of time in academia with all of the critical commentary, abusive behavior, and the fact that you gained an incredibly specific skill set. But I promise, you really really do have abilities and resources that you can trade for money. It might take a while to find those and to know how to market them, but you do have skills. 

While it's not universally true, most people who are potential Post Ac's don't completely understand that life can be pretty darn marvelous on the other side of the ivory tower. It's certainly not perfect, there are substantial differences to academic life and it can be hard in it's own way. But there is some evidence that you will (gasp) be happier if you leave academia. 

> "I didn't have a choice: I wanted to stay in academy but couldn't find a job.  Or at least wasn't willing to pursue post-docs outside the country in order to eventually get a job.  I guess during the time I was feeling the height of that rejection I wish I knew how many smart people in my field who are outside academia and happy" - Anonymous 

>"You're not worthless, and neither is your degree. Academia is great at convincing us we have no value. If you can get yourself to a place where you see the value in yourself and your abilities/education beyond academia, you'll start seeing possibilities again. And that's a really hopeful, abundant feeling." - Anonymous 

## How Long Will It Take?

For people who are struggling with the idea of leaving academia, an early question is "How long will it take me to find a job?" and also "How long will it take for me to feel better about this?" Obviously the answer is the intensely unsatisfying: it depends. 

With all honesty though, the process does take time. Possibly more time than you might want it to. Good things can happen quickly and you can get a job relatively fast, but you also are going to find that the recovery process is not something you can tackle in a month or even a couple of months. It will likely be measured in years. 

Which is another reason for a resource like this. Many of us who are writing and contributing to this are out of academia but we STILL find ourselves grappling with the experience now even years later. We still struggle with some of the hurts of our grad student and professorial years. We still struggle with putting ourselves out there and dealing with imposter syndrome, perfectionism and more. 

>" Prepare for the transition, read others' stories, know that it may take 3 years before you feel 'normal' again." - Anonymous 

> "Don't think this will be a quick transition. So many people told me it takes 3 to 6 months to adjust to a new job, but none of those people understood that a transfer out of academia is far different from switching jobs. Anticipate the adjustment taking no less than a year, but likely several more. " - Anonymous 

## Resources

There are a lot of resources throughout the syllabus but these are some of the main resources we've found that have helped us with the task considering academic recovery. 

* [The Professor is In](http://theprofessorisin.com/)

>"Karen has some really good non-academic career advice for free on her blog!"
>"Breaking down the myths and socialized beliefs about academic jobs" 

* [Imagine Ph.D.](https://www.imaginephd.com/)

* [Beyond the Professoriate](https://community.beyondprof.com/) 

>"Straight tips and courses, as well as conferences, that help you navigate the post-ac world. Real strategies and homework even!" 

* [Wild Mind Collective](http://www.wildmindcollective.com/) 

* [What I Wish I Had Known: Post Academic Women and Their Advice for Leaving the Academy - Beth M. Duckles](https://static1.squarespace.com/static/5a0cc397f09ca473053aea14/t/5aa700b071c10baf62f8ea88/1520894128791/What+I+Wish+I+Had+KnownFINAL.pdf)  

* [Perel, Greta - "What Happens When Academics Quit? Good Things it Turns Out."](https://www.timeshighereducation.com/blog/what-happens-when-academics-quit-good-things-it-turns-out)



## Homework 
We're going to offer some "homework" assignments in each section which will ask you to take what we've talked about and do some reflection. We encourage you to do the assignments that provoke a strong reaction in you. 

### Metaphors Exercise 
We often use metaphors in academic recovery that can help us to understand the challenges we've faced as academics. In this exercise there will be a series of questions that ask you to look at different metaphors that might help you tell your stories and to be intentional about which stories make the most sense for you. 

Grab a piece of paper and set a timer to spend 10 minutes writing on each metaphor. 

*1) Academia as a Relationship*  
If you were to describe your time in academia as a romantic relationship, what would that look like? What were you attracted to? What were your hopes and fears about the relationship when you started it? When did the relationship change? Did academia become an unrequited love? an indifferent partner? an abusive partner? Was academia aware of your needs? What were the good times like? What were the crappy times like? 

What does the ending of the relationship look like for you? Is it a painful divorce? An amicable parting of ways? A tentative separation? Did you break up with academia? Did academia break up with you? Was (is) your relationship with academia "complicated"?   

*2) Academia as an Addiction* 
If you were to refer to academia as something you are addicted to - what is the part that entices you? What is it about academia that is seductive and calls you back to it? Consider a high point of your academic time, what was it that you enjoyed about the academic system? What did you want more of?

Was there anything you weren't able to control in academia? The system itself? The job market? Your professors or your advisor? The university? The students? The negative comments and critiques? The results of the publishing process? Where did you feel powerless?  

* (Life After Academic - Jet)[http://lifeafteracademic.blogspot.com/2012/03/steps-for-recovering-academics.html]

*3) Academia as an Ivory Tower * 
Where were you separated from others in the course of being an academic? Were there any instances when you were not able to communicate with friends or family about what was happening? What was esoteric and hard to explain about the time you had in the academy? Where did you feel isolated? Were there times when you felt like the only person who had ever felt what you were feeling? 

*4) Academia as a Cult*  
What did you believe about the academy that turned out not to be true? What were the behaviors that you were encouraged to do in order to be a "better" academic that were destructive of your individuality and your self-concept? Did the system benefit from your work in ways that were harmful to you? 


** Let me be clear that academia is not actually a substance or a cult or an actual total institution but instead a set of institutions. This exercise is not meant to indicate that academia is the same as being addicted to as substance or being inside a cult, but rather to begin to explore where we were seduced by the system, where we see ourselves as powerless and how the system itself reinforced those things. ** 

 


