---
title: "Emotions"
---

In this section we're going to go through some of the specific emotional states that people have felt when leaving the academy. Those who write books and create workshops that help people do their human homework often do not focus specifically on the challenges that people who leave the academy face. Furthermore, academics who leave can be reticent to talk about their emotional states openly. We'll talk a little bit about why that might be the case and go deeper into a discussion of what we can do about this.  

In this unit, we're going to go through some of the emotional states that we have experienced and witnessed others experiencing. We're going to talk about the specific challenges some of us have faced. We do this in order to normalize these challenges and to make it clear that you're not alone if you feel these things. 

The goal here is to 

To support this discussion, we'll refer to our own experiences, share insight from folks who have written on these topics 

That said, there is a growing field of so called "quit lit" and others who are becoming more open about what they've experienced. 


