---
title: "EndingTheRelationship"
output: html_document
---
# Ending Your Relationship with Academia 

It’s that time of the year when school will be back in session (if it isn’t already) and many of us who have spent a large portion of our lives pacing ourselves via the academic calendar get that fall feeling. We see shiny new notebooks stacked up in stores, we start to notice the days getting a wee bit shorter and some of us start feel conflicting emotions. 

On the one hand, I used to love those fresh new notebooks with crisp clean pages and brand new clicky pens. On the other hand, academia and I are no longer… a thing. There is no classroom for me to stress about, no syllabus for me to procrastinate on writing and no 

Are you one of those people too? I figure there are three types: 1) Academia broke up with you 2) you broke up with academia or 3) You and academia have a complicated relationship. 


## Academia broke up with me
- I’m a graduate student and I didn’t pass my exams/my dissertation. 
- I’m a graduate student and I didn’t get an academic job but I’m graduating anyway. 
- I’m visiting/adjunct professor and this job is ending. 
- I was denied tenure. 

If academia broke up with you, there is likely a disconnect between what you wanted to have happen and what happened and this manifests usually as strong emotions like grief and a sense of loss, anger and sadness. This is a set of emotions that you need to go through. There’s also probably a sense that you’re not sure WTF to do next. You put so much of yourself into this and it did not work. You may find yourself doing some self-sabotage and  

## I broke up with Academia  
- I am too physically/mentally/emotionally ill to keep doing this.
- I was abused (emotionally/verbally/sexually). 
- I can’t make enough money/pay back my loans with this job. 
- I don’t want tenure here. 
- I don’t believe in what I’m doing anymore. 
- My family/children are in need and I have to be with them. 
- My partner got a job somewhere else and it was too good to turn it down. 
- I got a job offer and there were too many good reasons to take it.

While difficult, you did have a choice to stay or to go and this provides both a measure of comfort as well as (if you’re the kind of person who second guesses themselves) some anxiety. You may not fully know if this was the absolute right choice, but it might have been the right choice for your family, partnership, health, long term financial future and your heart and soul. If that is true for you, please know that all of these are entirely valid reasons to leave a job. 

You will likely know all of this and still feel a sense of loss. The difference is that you will have had more time in your discernment process to understand that this loss has some upsides. That’s not to say that leaving academia was necessarily what you wanted, but you may have felt that you had a choice. 

You still likely have the WTF do I do question. And you’re figuring out what happens next for you. 

## It’s not a great relationship 
- I’m a visiting/adjunct and I am not making ends meet. 
- I’m not a cis, hetero white man so I experience microaggressions daily. It is not sustainable.  
- I need to live in a geographic location where I want to be.  
- My department is toxic. I can’t do this for much longer. 
- I’m a graduate student but the constant criticism/abuse is not good for me. I’m not sure about academia as a career. 
- I have an academic job, but there is an end date. What do I do if this academic thing doesn’t work? 
- I’m on the never-ending postdoc track and I just can’t do another one.
- I don’t know who I’d be if I’m not a teacher but everything else besides my students is awful. 
-  I’m losing faith in what I’m doing. 
This is a challenging place to be because the situation you’re in right now probably feels pretty shitty and you’re not sure that you want to keep doing it. At the same time.  


There are three things I will say throughout the entirety of this book and I will repeat them in as many ways as possible 1) You are not alone 2) You have skills and 3) It can get better. 

#You Are Not Alone

Regardless of your experience, there are others who have had similar experiences and who have left the academy. There is even some evidence that you will (gasp) be happier if you leave. 

There are a myriad of people out there who are doing work that will help you even if you have no money, there are books you can check out from the library, concrete steps you can take and people who will talk to you. 

We will start with general resources and then follow up with specific resources for certain groups. 

## Readings

- What I wish I had Known - Beth M. Duckles 
- [The Professor is In](http://theprofessorisin.com/)
- [Imagine Ph.D.](https://www.imaginephd.com/)
- [Beyond the Professoriate](https://community.beyondprof.com/) 
- [Perel, Greta - “What Happens When Academics Quit? Good Things it Turns Out.”](https://www.timeshighereducation.com/blog/what-happens-when-academics-quit-good-things-it-turns-out)


