---
title: "Human Homework"
---

# Doing your Human Homework

Leaving the academy is a huge life shift and as the child of two psychologists (yes I know), I strongly encourage post acacadmics to "deal with your shit". Or as my mom used to call it: do your human homework. 

Human homework is the act of finding some way to honestly reflect on and work with any kind of dissonance or disruption within yourself. It often involves truth telling about challenging experiences you've had and walking through the stories you've told and the emotions that resulted.

It is not avoiding what happened, or pretending it didn't happen or trying to numb out. It is facing ourselves. I encourage you to do this because by facing what you've experienced, you are more able to heal and be a whole person. 

We never really finish doing our human homework, so this isn't something you accomplish (although maybe enlightened people are done? I don't know - I'm not enlightened). For most, human homework is a set of questions, or a process that you work through when you're facing tough times. It's about being deeply honest with ourselves about experiences that called into conflict our core ideas about the way the world works and what we are doing here.

There are about as many ways to do human homework as there are people in the world. There are also a lot of people who do this work under the auspices of psychology, self-help, 

## Transitions 

When you're going through transitions or difficult times doing this kind of work is vital because we are usually experiencing some sort of disruption in who we are, what we do, what we have to offer. There can be very real, very important reasons why you might not want to face all of this emotion work. Not the least of which is that you have deep trauma or childhood pains. So I strongly urge you to be gentle with yourself and to get support in doing this work. Trust yourself when something feels TOO delicate to approach. But instead of running away, consider just noting to yourself that this is not something you can approach and with as much compassion as you can, promising yourself that some day you will work with this. 

## Blocks for Academics in Doing Human Homework

One of the biggest imepdements to doing this work for people leaving academic positions is that many of us who are making these big transitions are also going through financial challenges at the same time. It's can be very hard to do deep emotional work on yourself when you don't have any money. Heck the scarcity of not having money ITSELF can more deeply aggrivate the emotional challenges you're facing. This is entirely real, you're not making this up and I'm sorry if that's where you are right now. 

Yet you CAN still do human homework without it costing money, I promise. There are a ton of resources below, go to the library and look through the books you see until one of them speaks to you and (this is important) *do the exercises in the book*. I know you can find a pencil and some paper and write. Do that. 

Consider also that there are places that have resources for you even if you don't have money. I know you're highly educated and may have some shame about not having as large of a bank account as you might want. That said, you're not helping anyone if you're not in good shape yourself. Consider asking for a price break because of economic hardship. Consider modalities where you can work with students or interns who are learning how to do stuff and can still give you quality care. Ask for help when you need it. 

Another block for many academics, is the capacity to turn our very well-honed critical lenses onto the whole idea of doing any human homework. In fields where we pride ourselves on being unbiased, looking at our inner landscape can be frightening and deeply challenging to our core beliefs. We may out of hand reject anything that is not scientifically based. We may see one thing on a list and reject it out of hand because it contains something we judge to be "nonsense". If you are an atheist or agnostic, you may find any mention of a higher power, God or even meditation or religion to be offputting and thus not worth your time. 

In fields where there is a belief that a "good" practitioner in the field has already dealt with these things, there can be a block to being someone who has to do more work or to trying something that is not sanctioned by your field. You might have opinions around subfields or authors, you might be resistant to something you think of as "not real" or which another person has said doesn't work. 

You may also have beliefs around what people would think of you if they knew you were doing your human homework. You might believe that colleagues or former students might judge you for and believe you weren't "good enough" because you had to do this. You might think that doing work like this makes you "weak" or "stupid". 

This is all resistance to doing the work. 

I'm not going to take a stand on what you should do. I respect that you come to this with beliefs about what is real and what is hogwash. I'm not trying to change your mind or question your core beliefs. I'm trying to encourage you become more whole. 

I honestly do not care what method you consider best to examine your inner landscape and I won't judge you if you tell me that what works for you is shamanic visioning or Freudian psychotherapy or Bible study or an online program or writing love letters to your soul in your journal. As long as you're doing the work, that's what matters and what will make you a more whole and effective person.  

And, I'll go even further. I believe that ALL people need to do their human homework in order to be whole. All of us need to take time to investigate challenging experiences, to reaffirm our core beliefs and to heal from disruptive events. All of us. 
The crux: *I don't care what kind of human homework you do. Just do something. * 

If you find yourself deciding NOT to examine what happened because of INSERT JUDGEMENTAL STATMENT HERE, name it for what it is: resistance. Then pick a book or resource from the list below that looks the least offensive to you and try it. Something is always better than nothing when it comes to dealing with your shit. 

## Human Homework Resources 

This list of resources is just a starting place. You might find something completely different that's not on this list. Totally fine (though feel free to tell us what it is!). 

Some of these resources might intrigue you, while others may turn you off. Just find the resources or methods that make sense to you and work with those. 

Try your best to let go of any judgement about what other people find useful or how anyone else might judge you about doing this work. None of that matters. This is about you finding what works for you and dealing with your shit. 

If you have other suggestions of resources for doing your human homework please contribute them.  


### Academics Doing Human Homework 
* [Brene Brown](https://brenebrown.com/) Brene Brown is a professor of social work at UT Austin who did a [TEDx talk that went viral](https://www.ted.com/talks/brene_brown_on_vulnerability?language=en) about the power of vulnerability. She has a [follow up talk about listening to shame ](https://www.ted.com/talks/brene_brown_listening_to_shame) and has written several books based on her research. Among them are [Rising Strong](https://www.amazon.com/Rising-Strong-Ability-Transforms-Parent-ebook/dp/B00P5557G2/ref=sr_1_1?ie=UTF8&qid=1534878505&sr=8-1&keywords=rising+strong), [Daring Greatly](https://www.amazon.com/gp/product/1592408419/ref=dbs_a_def_rwt_bibl_vppi_i1) and the [Gifts of Imperfection](https://www.amazon.com/gp/product/159285849X/ref=dbs_a_def_rwt_bibl_vppi_i0).  
* [Kristen Neff](http://self-compassion.org/) Her book on [Self-Compassion](https://www.amazon.com/Self-Compassion-Proven-Power-Being-Yourself-ebook/dp/B004JN1DBO/ref=sr_1_3?s=books&ie=UTF8&qid=1534958798&sr=1-3&keywords=Self+Compassion) works with existing research and explores how to cultivate and create practices of self-compassion in your life. Her website includes meditations and training programs. 
* [Parker Palmer and the Center for Courage and Renewal](http://www.couragerenewal.org/) A former academic, Parker writes about his experiences and share insights from the Quaker tradition and his time with the retreat center Pendle Hill. His books include [Let Your Life Speak](https://www.amazon.com/dp/B001C34LL8/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1) and [A Hidden Wholeness](https://www.amazon.com/gp/product/B0029U1RGA/ref=dbs_a_def_rwt_hsch_vapi_taft_p1_i3). He works with the Center for Courage and Renewal to create retreats and other seminars and his books focus on connecting to your purpose in life.  
* [Martha Beck](https://marthabeck.com/) Martha is a former academic who has written memoirs, self help books and has created a tribe of people who are focused on finding direction. Among her books: [Finding Your Own North Star](https://www.amazon.com/Finding-Your-Own-North-Star-ebook/dp/B0019O6IXE/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1534958698&sr=1-1&keywords=martha+beck), [Steering By Starlight](https://www.amazon.com/gp/product/1605298646/ref=dbs_a_def_rwt_bibl_vppi_i2), [Finding Your Way in a Wild New World](https://www.amazon.com/gp/product/1451624603/ref=dbs_a_def_rwt_bibl_vppi_i1).
* [Viktor Frankl's](https://en.wikipedia.org/wiki/Man%27s_Search_for_Meaning) book "A Man's Search for Meaning" is written by a psychologist, chronicling his experiences in Auchwitz and how he came out of that experience to find meaning in his life. 

### Books and Programs 
* [Tara Mohr](https://www.taramohr.com/) is a woman who became frustrated with how many women in her life were not doing what they most wanted to do and were "playing small" in their lives. She created a book and subsequent workshops and online programs to help women. her work is called [Playing Big](https://www.taramohr.com/the-playing-big-book/).  
* [The Sedona Method](https://www.sedona.com/Home.asp) The Sedona Method is a simple technique of asking a sequence of questions that encourages the practitioner to "let go" of whatever emotions they are feeling in the moment. The technique is simple, but the book traces a number of ways to integrate this into one's life. There is a book and workshops, apps and online materials. 
* [Byron Katie](http://thework.com/en) does what she calls  "The Work" which asks the participant to engage with their experiences in the world and ask questions about what they believe. She has several books and workshops but the basics of working with her method is freely available on her website as are videos of her working with people.  
* The Road Less Traveled - Peck 
* [Strengths Finder] 
* Fire Starter Sessions - Danielle LaPorte 
* Nonviolent Communication 


* [Transitions Book] - William Bridges 
* ["Uncertainty: Turning Fear and Doubt into Fuel For Brilliance - Jonathan Fields](http://www.jonathanfields.com/)
* [The Dance of Anger - Harriet Lenrner](https://www.harrietlerner.com/)

### Psychological/Theraputic Resources 


### Bodywork and Physically Oriented Therapies
* [Hakomi Method](http://hakomiinstitute.com/) - Mindful Somatic Psychology 
* [Wendy Palmer](http://www.leadershipembodiment.com/) is an Aikido teacher and leadership consultant who works on how to embody the principles of the nonviolent martial art in working with others. 

### Meditation Resources 
* Pema Chodron 
* ["The Power of Meditation: A 28 Day Program - Sharon Saltzberg](https://www.sharonsalzberg.com/)
* Adyashanti 

### Communities 
* Twelve Step programs (AA, AlAnon, NA, etc.)
* Landmark Forum
* More to Life


- Last Mask Shamanic Center 

- The Big Leap (???)
- 
