# Getting a Job

There are libraries of books out there on how to find a job and a ton of people whose stated life purpose is to assist people in finding their life's work. That said, it can be somewhat overwhelming to approach these libraries and armies of people when you’re a post academic because you have some very specific challenges that aren't always fully addressed in the traditional field of job hunting. 

You might wonder:
- Who would hire me? 
- What skills exactly do I have? 
- How do I turn my CV into a resume? 
- How do I talk about my research/papers/work to non academics?
- How do I market my skills? (and by the way marketing is a dirty word and I'm bad at it) 
- What if I want to do something completely different? 

The purpose of this lesson is NOT to answer all these questions (sorry!) but instead to point you towards resources we found helpful, give you some homework assignments that have helped us and to remind you that you are not alone, others have gone through this. 

Let me now remind you that 1) other people have done this and it is doable 2) you've got skills and 3) you might be surprised to find that your life and work could be pretty awesome in the end. No promises but really, many of us feel that way. 

First off: we know that you have skills. Even if you have the most esoteric dissertation in the world, you have skills and often can teach them or use them in service to all kinds of projects. Consider what you did love about academia. Was it reading? Writing? Teaching? Was it the content you were working on? Was it the methods you were using? Did you like the meetings or prefer to hide out in the lab/library/archives? Consider your answers to these questions as you look for your job and try to find places where those skills are valued.  

Second, the path of finding your post ac job can be trial and error. It often does not follow a clear path and there isn’t anyone else who can know what the next step is for you to take. It can be bewildering, frustrating and incredibly scary for academics who have had the path laid out for them (take these classes, then do these exams, then write this paper etc). This kind of figure-it-out-as-you-go mentality is actually normal for non academics. If you need to be reminded of this, go talk to a friend who never went to grad school and ask them how they got their current job. You might be surprised. 

Third, you gotta pay your bills. Don’t discard jobs that are completely different than your academic work, if they fit for you and make you happy. There is no shame in doing work that is non academic to make ends meet. Do side gigs if you need to, start up an etsy shop, work with high school kids on their SAT prep, teach art classes, do freelance writing or editing. Consider arranging flowers, being a cheesemonger, becoming a sommelier, a bike mechanic, doing community organizing, running online seminars, Let me reiterate, there is no shame in any of these jobs. Or rather, you can feel ashamed if you really want to but you might consider that most people are not judging you. 

## Resources

### Books Focused on Academics 
- [So What Are You Going To Do With That? - Susan Basalla](https://www.amazon.com/What-Are-You-Going-That/dp/0374526214)
- [The Professor is In - Karen Kelsky](http://theprofessorisin.com/buy-the-book/)

### Websites
- [Jobs on Toast](http://jobsontoast.com/)
- [Versatile Ph.D.](https://versatilephd.com/)

### Books on Offbeat Jobs 
- [Born for This: How to Find the Work You Were Meant to Do - Chris Guillibeau](https://bornforthisbook.com/)
- [How to Be Everything: A Guide for Those Who (Still) Don't Know What They Want to Be When they Grow Up](https://www.harpercollins.com/9780062566652/how-to-be-everything/)
- [Leap: Leaving a Job with No Plan B to Find the Career and Life You Really Want - Tess Vigeland](https://www.tessvigeland.com/)
- [Working Identity: Unconventional Strategies for Reinventing your Career - Herminia Ibarra](https://herminiaibarra.com/books/)
- [The Art of Nonconformity - Chris Guillibeau](https://chrisguillebeau.com) 
- [Weird in a World That's Not: A Career Guide for Misfits, F*ckups, and Failures by Jennifer Romolini](https://www.harpercollins.com/9780062472724/weird-in-a-world-thats-not/)

### Articles
- [Benefits of a Non Linear Career Path](https://medium.com/design-leadership/benefits-of-a-non-linear-design-career-path-d0add49a90c8)
- [Post Acs are Happier than Academics](https://www.insidehighered.com/news/2017/12/18/study-humanities-and-social-science-phds-working-outside-academe-are-happier-their?utm_source=Inside+Higher+Ed)

### Entrepreneurship
- [Disrupt Yourself: Putting the Power of Disruptive Innvoation to Work - Whitney Johnson](https://www.amazon.com/Disrupt-Yourself-Putting-Disruptive-Innovation-ebook/dp/B00VQOA26Q)
- [$100 Startup - Chris Guillibeau](https://www.amazon.com/dp/B0067TGSOK/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1)
- [Side Hustle: From Idea to Income in 27 Days - Chris Guillibeau  Book and Side Hustle School](https://sidehustleschool.com/) 

### Marketing 
- [Book Yourself Solid - By Michael Port](https://www.amazon.com/Book-Yourself-Solid-Reliable-Marketing/dp/0470643471)


## Homework 
1. Write down ten jobs you would like to do. Don’t think about it, just write them down. Doesn’t matter if they’re silly or strange. Feel free to put circus performer, professional basketweaver or person who does nature walks for a living. Do this every day for a week. 
2. Look up the concept of [Ikigai](https://en.wikipedia.org/wiki/Ikigai) or your "Reason for Being". Print out a copy of the diagram (a google search here will help) and fill in your skills/projects so that you can see where your skills fit. Ask questions of the things that you fill in. For instance, if one task fits into the category of What you love and what the world needs, how might you find a way to also get good at the task and/or to get paid for it?  
3. Ask someone you trust to tell you what they think you’re good at. Listen without interrupting. Write down what they say. 

