#You Are Not Alone

This unit reminds you that regardless of your experience, there are others who have had similar experiences and who have left the academy. There is even some evidence that you will (gasp) be happier if you leave. 

There are a myriad of people out there who are doing work that will help you even if you have no money, there are books you can check out from the library, concrete steps you can take and people who will talk to you. 

We will start with general resources and then follow up with specific resources for certain groups. 

## Readings

- What I wish I had Known - Beth M. Duckles 
- [The Professor is In](http://theprofessorisin.com/)
- [Imagine Ph.D.](https://www.imaginephd.com/)
- [Beyond the Professoriate](https://community.beyondprof.com/) 
- [Perel, Greta - “What Happens When Academics Quit? Good Things it Turns Out.”](https://www.timeshighereducation.com/blog/what-happens-when-academics-quit-good-things-it-turns-out)

## Resources for Women 
Women often face very specific challenges with leaving the academy. There are a number of resources that may help you work with and heal from these challenges as well as assisting you in getting your story back into your own hands.  

-  [Tara Mohr, Playing Big](https://www.taramohr.com/book/) 
> “Gave me lots of solid information about women and ambition, and eventually connected me to smart women also trying to figure shit out.


## Resources for People of Color 



